[package]
name = "multisig"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Currently need std because of miniserde
nesdie = { path = "../../", features = ["std"] }
nesdie-collections = { path = "../../collections", features = ["legacy"] }
borsh = { version = "0.9", default-features = false }
miniserde = "0.1"
bs58 = "0.4"
base64 = "0.13"

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"

